# Generated by Django 5.2.7 on 2025-10-05 01:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Nombres"),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Dirección")),
                ("phone", models.CharField(max_length=20, verbose_name="Teléfono")),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, null=True, verbose_name="Información Adicional"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.CreateModel(
            name="Raffle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nombre de la Rifa"),
                ),
                (
                    "year",
                    models.IntegerField(
                        default=2025,
                        validators=[django.core.validators.MinValueValidator(2000)],
                        verbose_name="Año",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="logos/",
                        verbose_name="Logotipo",
                    ),
                ),
                (
                    "product_images",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="Imágenes de Productos",
                    ),
                ),
                (
                    "social_links",
                    models.TextField(
                        blank=True, null=True, verbose_name="Links de Redes Sociales"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rifa",
                "verbose_name_plural": "Rifas",
                "unique_together": {("name", "year")},
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.PositiveIntegerField(verbose_name="Número de Boleto"),
                ),
                (
                    "qr_code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Código QR de Verificación",
                    ),
                ),
                (
                    "sold_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Venta"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="raffles.customer",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "raffle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="raffles.raffle",
                        verbose_name="Rifa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boleto",
                "verbose_name_plural": "Boletos",
                "unique_together": {("raffle", "ticket_number")},
            },
        ),
    ]
