# Generated by Django 5.2.7 on 2025-10-05 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Plantilla"
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#FFFFFF", max_length=7, verbose_name="Color de Fondo"
                    ),
                ),
                (
                    "font_color",
                    models.CharField(
                        default="#000000",
                        max_length=7,
                        verbose_name="Color de la Fuente",
                    ),
                ),
                (
                    "background_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ticket_backgrounds/",
                        verbose_name="Imagen de Fondo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de Boleto",
                "verbose_name_plural": "Plantillas de Boletos",
            },
        ),
        migrations.AddField(
            model_name="raffle",
            name="ticket_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="raffles.tickettemplate",
                verbose_name="Plantilla de Boleto",
            ),
        ),
    ]
