# Generated by Django 5.2.7 on 2025-10-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0002_tickettemplate_raffle_ticket_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="favicons/",
                        verbose_name="Favicon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del Sitio",
                "verbose_name_plural": "Configuración del Sitio",
            },
        ),
    ]
