# Generated by Django 6.0 on 2026-01-03 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0003_sitesettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raffle",
            name="year",
            field=models.IntegerField(
                default=2026,
                validators=[django.core.validators.MinValueValidator(2000)],
                verbose_name="Año",
            ),
        ),
    ]
