# Generated by Django 6.0 on 2026-01-03 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0004_alter_raffle_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="raffle",
            name="draw_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha y Hora del Sorteo"
            ),
        ),
        migrations.AddField(
            model_name="raffle",
            name="winning_ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="won_raffle",
                to="raffles.ticket",
                verbose_name="Boleto Ganador",
            ),
        ),
    ]
