# Generated by Django 6.0 on 2026-01-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0005_raffle_draw_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="identification",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Cédula/RUC/Pasaporte",
            ),
        ),
    ]
