# Generated by Django 6.0 on 2026-01-03 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0006_customer_identification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raffle",
            name="social_links",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Links de Redes Sociales (Texto antiguo)",
            ),
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(
                        max_length=50, verbose_name="Nombre de la Plataforma"
                    ),
                ),
                ("url", models.URLField(verbose_name="Enlace")),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="social_icons/",
                        verbose_name="Icono",
                    ),
                ),
                (
                    "raffle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links_list",
                        to="raffles.raffle",
                        verbose_name="Rifa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Red Social",
                "verbose_name_plural": "Redes Sociales",
            },
        ),
    ]
