# Generated by Django 6.0 on 2026-01-04 19:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0007_alter_raffle_social_links_sociallink"),
    ]

    operations = [
        migrations.CreateModel(
            name="DolibarrIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="Secret key to validate requests from Dolibarr",
                        max_length=64,
                        unique=True,
                        verbose_name="API Key",
                    ),
                ),
                (
                    "tickets_per_amount",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Boletos por Monto"
                    ),
                ),
                (
                    "amount_step",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        max_digits=10,
                        verbose_name="Monto Base ($)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, verbose_name="Integración Activa"
                    ),
                ),
                (
                    "default_ticket_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Precio del Boleto (Registro)",
                    ),
                ),
                (
                    "active_raffle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="raffles.raffle",
                        verbose_name="Rifa Activa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Integración Dolibarr",
                "verbose_name_plural": "Integración Dolibarr",
            },
        ),
    ]
