# Generated by Django 6.0 on 2026-01-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0008_dolibarrintegration"),
    ]

    operations = [
        migrations.CreateModel(
            name="DolibarrTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Referencia Dolibarr (Factura/Pedido)",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                (
                    "tickets_count",
                    models.IntegerField(verbose_name="Boletos Generados"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
