# Generated by Django 6.0 on 2026-01-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0009_dolibarrtransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Correo Electrónico"
            ),
        ),
    ]
