# Generated by Django 6.0 on 2026-01-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffles', '0010_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
