# Generated by Django 5.2.11 on 2026-02-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffles", "0011_allow_nullable_phone_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="dolibarrtransaction",
            name="facture_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID interno de la factura en Dolibarr (no cambia al re-validar)",
                null=True,
                verbose_name="ID Factura Dolibarr",
            ),
        ),
    ]
